In [ ]:
import numpy as np
np.random.seed(7)

# Activation Functions

Theshold  ( bias)

            f(x) = 0 for x< t and 1 for x>= t

Linear

            f(x) = x

Sigmoid

            f(x) = 1/(1 + e^-x )           

TanH

            f(x) = tanh(x)
            
ReLU (Rectified Linear Unit)

            f(x) = max(0,x)

In [ ]:
I = np.array([1,2,4])
W = np.array([0.5,0.3,0.1])
I*W

array([0.5, 0.6, 0.4])

In [ ]:
X = sum(I*W)# (I*W).sum()
X

1.5

In [ ]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(y_pred): # sigmoid derivative is reduced to value y_pred * (1-y_pred)
    return y_pred * (1 - y_pred) # here y_pred = 1/(1 + np.exp(-x))

In [ ]:
def relu(x):
    return max(0,x)

def relu_derivative(x):
    """
    df/dx = 0 for x < 0 and 1 for x>0
    for x==0 derivative is undefined
    FOR ALL PRACTICAL PURPOSES
    in implementation when x==0
    we can return 0 / 1
    Here we decide to return 0
    """
    result = None
    if x > 0:
        result = 1
    elif x <= 0:
        result = 0
#     else:
#         print("undefined")
    return result

In [ ]:
#Input datasets
## XOR Gate Data
#X or known variables
inputs = np.array([[0,0],[0,1],[1,0],[1,1],[0,0],[0,1],[1,0],\
                   [1,1],[0,0],[0,1],[1,0],[1,1]])
inputs = inputs.T
#Y or un-known variables
expected_output = np.array([[0],[1],[1],[0],[0],[1],[1],[0],\
                           [0],[1],[1],[0]])
expected_output = expected_output.T

# Configure the Neural Network

## Input Layer -->
Here neurons are just place holders , there is no processing

ONLY input is taken and given to first hidden layer

## No of Input Neurons in input layer::
Same as no of input columns

## No of Output Neurons in output layer

+ Based on Type of the output whether classification or regression problem

1. Classification ::

    a. With One hot encoded  ::
            No of output neurons = No of output classes
    b. Without One hot encoding
            No of output neurons = 1

2. Regression ::

    a. If one output variable :
            No of output Neurons = 1
    b. If multiple output variables :
            No of output Neurons = No of output variables

In [ ]:
# How to decide no of Neurons in input layer and output layer
# Thumb rules for hidden layers
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,4,1

# How to decide Hidden Layer Nuerons

#### NOTE ::: There is NO thumb rules for this !!!!

## You are required to tune :::

### No of Hidden Layers
### No of Neurons in each hidden layer

In [ ]:
inputs.shape, expected_output.shape

((2, 12), (1, 12))

# How To initialize Weights

+ Method 1: Sample weights randomly from uniform distribution ( and values between 0 to 1) In uniform distribution all possible values have same probability
+ Method 2 : Use pre existing values (Transfer Learning)
+ Method 3 : Constant Values --> Very old method, not used now

In [ ]:
#Random weights and bias initialization
hidden_weights = np.random.uniform( size=(hiddenLayerNeurons,inputLayerNeurons))
hidden_bias =np.random.uniform(size=(hiddenLayerNeurons,1))
output_weights = np.random.uniform(size=(outputLayerNeurons,hiddenLayerNeurons))
output_bias = np.random.uniform(size=(outputLayerNeurons,1))

In [ ]:
hidden_weights, hidden_weights.shape

(array([[0.07630829, 0.77991879],
        [0.43840923, 0.72346518],
        [0.97798951, 0.53849587],
        [0.50112046, 0.07205113]]),
 (4, 2))

In [ ]:
hidden_bias

array([[0.26843898],
       [0.4998825 ],
       [0.67923   ],
       [0.80373904]])

In [ ]:
output_weights

array([[0.38094113, 0.06593635, 0.2881456 , 0.90959353]])

In [ ]:
output_bias

array([[0.21338535]])

# How to Decide no of Epochs

## Early Stopping Method

In coding enable stopage of training when validation loss increases ( over fitting starts)

## Manual Method
1. Have a fixed no to begin with ( generally i prefer 100 epochs)

2. Check for underfitting or overfitting

3. When underfitting --> Increase the no of epochs

4. When overfitting --> Decrease the no of epochs

In [ ]:
epochs = 150000

In [ ]:
lr = 0.5

In [ ]:
print("Initial hidden weights: ",end='')
print(*hidden_weights)
print("Initial hidden biases: ",end='')
print(*hidden_bias)
print("Initial output weights: ",end='')
print(*output_weights)
print("Initial output biases: ",end='')
print(*output_bias)

Initial hidden weights: [0.07630829 0.77991879] [0.43840923 0.72346518] [0.97798951 0.53849587] [0.50112046 0.07205113]
Initial hidden biases: [0.26843898] [0.4998825] [0.67923] [0.80373904]
Initial output weights: [0.38094113 0.06593635 0.2881456  0.90959353]
Initial output biases: [0.21338535]


# Training

## Error Function:

Ideal Error should be a perfect convex curve with single global minima (no local minimas)

Error curve is assumed to be continuous and a differentiable function

#Weight Update Rule

W = W - lr * delta_change

where

delta_change = error_at_layer * slope_of_layer_activation

lr is learning rate




In [ ]:
#Training algorithm
for _ in range(epochs):
    #Forward Propagation
    hidden_layer_summation = np.dot(hidden_weights,inputs)
    hidden_layer_summation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_summation)


    output_layer_summation = np.dot(output_weights,hidden_layer_output)
    output_layer_summation += output_bias
    predicted_output = sigmoid(output_layer_summation)

    #Backpropagation
    # derivative of loss wrt yp
    error = predicted_output - expected_output
    #derivative at output layer -(ya - yp) * (yp*(1-yp))
    d_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = output_weights.T.dot(d_output)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    #Updating Weights and Biases
    # derivate of loss wrt weight = inputs * derivative at layer
    o_derivative= hidden_layer_output.dot(d_output.T)
    output_weights -= o_derivative.T * lr
    output_bias -= np.sum(d_output,axis=1,keepdims=True) * lr
    # derivate of loss wrt weight = inputs * derivative at layer
    h_derivative = inputs.dot(d_hidden_layer.T)
    hidden_weights -= h_derivative.T * lr
    hidden_bias -= np.sum(d_hidden_layer,axis=1,keepdims=True) * lr

In [ ]:
print("\nOutput from neural network after",epochs," epochs: ")
for e,p in zip(expected_output, predicted_output):
    print("expected ", e, "predicted",p)


Output from neural network after 150000  epochs: 
expected  [0 1 1 0 0 1 1 0 0 1 1 0] predicted [0.00235981 0.99809911 0.99802359 0.00177694 0.00235981 0.99809911
 0.99802359 0.00177694 0.00235981 0.99809911 0.99802359 0.00177694]


In [ ]:
print("Final hidden weights: ",end='')
print(hidden_weights)
print("Final hidden bias: ",end='')
print(hidden_bias)
print("Final output weights: ",end='')
print(output_weights)
print("Final output bias: ",end='')
print(output_bias)

Final hidden weights: [[0.06160714 0.76685929]
 [0.43865633 0.72369203]
 [0.97284975 0.53230935]
 [0.47095693 0.03791046]]
Final hidden bias: [[0.23761466]
 [0.50030317]
 [0.664244  ]
 [0.73262481]]
Final output weights: [[ 0.08755892 -0.26240671 -0.06434509  0.57949139]]
Final output bias: [[-0.23311018]]
