In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,56,34,78,2])

In [ ]:
arr, type(arr)

(array([ 1, 56, 34, 78,  2]), numpy.ndarray)

In [ ]:
arr.shape

(5,)

In [ ]:
arr.size #Number of elements in the array.

5

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.itemsize

8

In [ ]:
arr1 = np.array([12.3,123])

In [ ]:
arr1, arr1.dtype

(array([ 12.3, 123. ]), dtype('float64'))

In [ ]:
arr1.itemsize

8

In [ ]:
arr1 = np.array(['cdac',123])

In [ ]:
arr1, arr1.dtype

(array(['cdac', '123'], dtype='<U21'), dtype('<U21'))

In [ ]:
arr1.itemsize

84

In [ ]:
arr2d = np.array([[1,2],[3,4]]) #Number of elements in the array.

In [ ]:
arr2d.shape, arr2d.size, arr2d.dtype, arr2d.itemsize

((2, 2), 4, dtype('int64'), 8)

In [ ]:
arr2d = np.array([[1,2],[3,4],[1,2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
arr3d.shape, arr3d.size, arr3d.dtype,arr3d.itemsize

((2, 2, 2), 8, dtype('int64'), 8)

In [ ]:
arr = np.array([3,2,3],dtype='int8')

In [ ]:
arr.dtype

dtype('int8')

In [ ]:
arrComplex = np.array([1,2,3],dtype='complex')

In [ ]:
arrComplex

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
arrComplex.dtype, arrComplex.itemsize

(dtype('complex128'), 16)

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
arr3d_zeros = np.zeros(arr3d.shape)

In [ ]:
arr3d_zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
np.empty((2,2,2,3),dtype='int')

array([[[[           203710589,                    0,
              2533313445691401],
         [    2533313445691401, -7898074167280402423,
              2533317544641924]],

        [[    2611769638912009,     2533313445691401,
           7522138995603079177],
         [     832716941857636,      541415013619557,
                             0]]],


       [[[                   0,   192411976291619940,
            112589990684262401],
         [   48137188522879332,  -623185598437392383,
            325551530598203792]],

        [[ 2694753899889490010,           8362000784,
                             0],
         [  120189815055450112,     2533274790395905,
           5144238392351457289]]]])

# arange()

In [ ]:
myRange = np.arange(20,1,-1) #start end step

In [ ]:
myRange

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2])

In [ ]:
myRange = np.arange(np.pi,np.pi*10,1)

In [ ]:
myRange

array([ 3.14159265,  4.14159265,  5.14159265,  6.14159265,  7.14159265,
        8.14159265,  9.14159265, 10.14159265, 11.14159265, 12.14159265,
       13.14159265, 14.14159265, 15.14159265, 16.14159265, 17.14159265,
       18.14159265, 19.14159265, 20.14159265, 21.14159265, 22.14159265,
       23.14159265, 24.14159265, 25.14159265, 26.14159265, 27.14159265,
       28.14159265, 29.14159265, 30.14159265, 31.14159265])

In [ ]:
myRange = np.arange(0.5,7.7,0.2)

In [ ]:
myRange

array([0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5, 2.7, 2.9,
       3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9, 5.1, 5.3, 5.5,
       5.7, 5.9, 6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3, 7.5])

In [ ]:
myRange = np.arange(np.pi,10*np.pi,np.pi)

In [ ]:
myRange

array([ 3.14159265,  6.28318531,  9.42477796, 12.56637061, 15.70796327,
       18.84955592, 21.99114858, 25.13274123, 28.27433388])

# Special case if step is having rounding off error

In [ ]:
myRange = np.arange(0.5,1.9,0.7)

In [ ]:
myRange

array([0.5, 1.2])

In [ ]:
myRange = np.arange(0,4.9,0.7)

In [ ]:
myRange

array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9])

# linearly spaced values

In [ ]:
np.linspace(0,1,5) # create n-1 parts

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,20,5) # create n-1 parts

array([ 0.,  5., 10., 15., 20.])

# Arithmetic Operation

In [ ]:
arr1=np.array([100,345,678,3456])
arr2=np.array([12,15,78,90])

In [ ]:
arr1+ arr2

array([ 112,  360,  756, 3546])

In [ ]:
arr1 -  arr2

array([  88,  330,  600, 3366])

In [ ]:
arr1 * arr2

array([  1200,   5175,  52884, 311040])

In [ ]:
arr1 * 100

array([ 10000,  34500,  67800, 345600])

In [ ]:
arr1 / 40 * 89 + arr2 * 10 + 100

array([ 442.5  , 1017.625, 2388.55 , 8689.6  ])

# exercise


In [ ]:
m1=np.array([78,98,85])
m2=np.array([96,77,80])
m3=np.array([99,91,78])

In [ ]:
# find percentage of every student

# create 2d array for all records and perform
#sum(), sum(axis=0), sum(axis=1)

a2d = np.array([m1,m2,m3])
print(a2d)
print(np.sum(a2d, axis=0))
print(np.sum(a2d, axis=1))

[[78 98 85]
 [96 77 80]
 [99 91 78]]
[273 266 243]
[261 253 268]


# Create array of random numbers

repeatition is allowed

In [ ]:
r_arr = np.random.randint(0,1000,(2,2))
#Return random integers from low (inclusive) to high (exclusive).

In [ ]:
r_arr

array([[637, 393],
       [  8, 436]])

In [ ]:
r_arr = np.random.randint(0,5,(4,5))

In [ ]:
r_arr

array([[0, 0, 3, 3, 3],
       [3, 2, 4, 1, 3],
       [3, 2, 2, 2, 1],
       [2, 1, 0, 4, 2]])

In [ ]:
r_arr = np.random.rand(10)

In [ ]:
r_arr

array([0.26671908, 0.93261129, 0.33375035, 0.27164772, 0.02424386,
       0.11791493, 0.84102292, 0.62526097, 0.70134972, 0.20005727])

In [ ]:
r_arr = np.random.rand(10,2)

In [ ]:
r_arr

array([[0.97130137, 0.2489816 ],
       [0.04041239, 0.85803822],
       [0.99387026, 0.96191112],
       [0.89183785, 0.79763452],
       [0.30094656, 0.53301615],
       [0.86995067, 0.76650988],
       [0.96306218, 0.97741416],
       [0.83145853, 0.19625342],
       [0.92039806, 0.03729928],
       [0.82368202, 0.60478847]])

# Matrix Operations

In [ ]:
A = np.array([[1,2],[3,4]])

In [ ]:
B = np.array([[100,200],[300,400]])

In [ ]:
A*B # element wise multiplication

array([[ 100,  400],
       [ 900, 1600]])

In [ ]:
A@B

array([[ 700, 1000],
       [1500, 2200]])

In [ ]:
A.dot(B)

array([[ 700, 1000],
       [1500, 2200]])

# Universal Functions

https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

In [ ]:
A = np.array([[1,2],[3,4]])

In [ ]:
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [ ]:
np.power(A,3)

array([[ 1,  8],
       [27, 64]])

In [ ]:
np.sin(A)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [ ]:
np.cos(A)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

# Numpy special representations for floating point values

+inf    -> + infinity

-inf    -> - infinity

nan     -> Not a Number



In [ ]:
A = np.array([[1,2],[3,4]])
A/0

/tmp/ipython-input-3720512564.py:2: RuntimeWarning: divide by zero encountered in divide
  A/0


array([[inf, inf],
       [inf, inf]])

# ravel  and flatten

In [ ]:
r_arr = np.random.randint(0,1000,(2,2,2))

In [ ]:
r_arr.ravel()

array([218, 213, 391, 991,   0, 212, 152, 145])

In [ ]:
for elem in r_arr.ravel():
    print("Element in array is : ")
    print(elem)

Element in array is : 
218
Element in array is : 
213
Element in array is : 
391
Element in array is : 
991
Element in array is : 
0
Element in array is : 
212
Element in array is : 
152
Element in array is : 
145


In [ ]:
for elem in r_arr:
    print("Element in array is : ")
    print(elem)

Element in array is : 
[[616 955]
 [129 987]]
Element in array is : 
[[102 993]
 [371  57]]


# concat

In [ ]:
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
y

array([[5, 6]])

In [ ]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((x, y), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

# add new axis

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [ ]:
row_vector = a[np.newaxis, :]
print(row_vector)
row_vector.shape

[[1 2 3 4 5 6]]


(1, 6)

In [ ]:
col_vector = a[:,np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

# vectorized conditions

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a<5)
print(a[a<5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ True  True  True  True]
 [False False False False]
 [False False False False]]
[1 2 3 4]


In [ ]:
a = np.array([1,2,3,4,5])
print(a[a%2==0])
print(a[(a>1)&(a<5)])

[2 4]
[2 3 4]


In [ ]:
a[2:5]#slicing the array::: start:end:step

array([3, 4, 5])

# vstack and hstack

In [ ]:
a1 = np.array([[1, 1],

               [2, 2]])

a2 = np.array([[3, 3],

               [4, 4]])

In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# reverse an array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

# Create a sample operation of neuron in numpy

fun neuron has two parameters

x : input array ( size n)

w : weights (size n)

bias : its a single value / constant

x & w are of same size

Step1 : calculate their element wise multiplication

Step2 : calculate sum of above multiplication and add bias to it

Step3 : return the value



In [ ]:
def neuron(x,w,bias):
    X = x*w
    X = X.sum() + bias
    return X

In [ ]:
x= np.array([10,20,30])

In [ ]:
w=np.random.rand(x.shape[0])

In [ ]:
w

array([0.26809235, 0.01697488, 0.28201312])

In [ ]:
bias = 100

In [ ]:
neuron(x,w,bias)

111.48081472873571